name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - feature/build

# 모든 명령어들을 특정 하위 폴더 안으로 들어가서 실행하도록 기본값(defaults)을 설정합니다.
defaults:
  run:
    working-directory: TicketDiary  # 🌟 여기에 pubspec.yaml이 들어있는 실제 폴더명을 적어주세요!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release --base-href "/TicketDiary/"

      - uses: actions/upload-pages-artifact@v3
        with:
          # 업로드할 폴더 경로 앞에도 폴더명을 붙여줍니다.
          path: TicketDiary/build/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
